version: '3.7'

services:
  postgres:
    image: postgres:16 
    container_name: product-database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: productdatabase
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

volumes:
  postgres_data:
