import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { SnackbarProvider } from "@/context/snackbarContext";
import { UserProvider } from "@/context/userContext";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <SnackbarProvider>
        <UserProvider>
          <body className={inter.className}>{children}</body>
        </UserProvider>
      </SnackbarProvider>
    </html>
  )
}
