version: '3.7'
services:
  database:
    image: mongo:4.4
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27018:27017'
    volumes:
      - ./db-data:/data/db